Updated build-and-push-to-dev.yml

diff --git a/ado-pipelines/build-and-push-to-dev.yml b/ado-pipelines/build-and-push-to-dev.yml
--- a/ado-pipelines/build-and-push-to-dev.yml
+++ b/ado-pipelines/build-and-push-to-dev.yml
@@ -5,12 +5,48 @@ parameters:
 - name: imageRepository
   displayName: imageRepository - the image repository you want to create (example. bd/pothenesxes)
   type: string
+# - name: project
+#   displayName: project - the project the repo is located at
+#   type: string
+- name: repo
+  displayName: repo - the repo the file is located at
+  type: string
+# - name: branch
+#   displayName: branch - the branch of the repo that the file is located at
+#   type: string
+# - name: changeImageOnWebapp
+#   displayName: changeImageOnWebapp - use true to also update the image on the webapp
+#   type: boolean
+# - name: performSmokeTest
+#   displayName: performSmokeTest - use true if you already chose to change image to also perform a smoke test on the webapp
+#   type: boolean
 - name: devContainerRegistry
   displayName: devContainerRegistry - the container registry to push the image in dev
   type: string
+# - name: qaContainerRegistry
+#   displayName: qaContainerRegistry - the container registry to push the image in qa and set the webapp
+#   type: string
+# - name: appName
+#   displayName: Name of the Web App
+#   type: string
+# - name: resourceGroupName
+#   displayName: resourceGroupName - the resource group where the application is located at
+#   type: string
+# - name: subscriptionName
+#   displayName: subscriptionName - the subscription where the application is located at
+#   type: string
+# - name: environment
+#   displayName: Environment - the environment the application is located at
+#   type: string
 - name: devServiceConnection
   displayName: devServiceConnection - the name of the service connection used in dev
   type: string
+# - name: qaServiceConnection
+#   displayName: qaServiceConnection - the name of the service connection used in qa
+#   type: string
+# - name: agentPool
+#   displayName: agent - the pool name that the build-and-push will run from 
+#   type: string
 - name: versionUpgrade
   displayName: versionUpgrade - the version to be upgraded ( major/minor/patch )
   type: string
@@ -143,3 +179,110 @@ jobs:
           docker push $devContainerRegistry.azurecr.io/$(imageRepository):latest
 
           echo "New tag: $(getImageRepositoryTags.newTag)"
+
+# - job: pushImageToQA
+#   displayName: PUSH IMAGE TO QA
+#   dependsOn: buildAndPushImage
+#   pool: 
+#     name: ${{ parameters.agentPool }}
+#   variables:
+#     newTag: $[ dependencies.buildAndPushImage.outputs['getImageRepositoryTags.newTag'] ]
+#   steps:
+#   - task: Bash@3
+#     inputs:
+#       targetType: 'inline'
+#       script: |
+#         imageRepository="${{ parameters.imageRepository }}"
+#         echo $imageRepository
+#         echo $(newTag)
+
+#         echo "[=] Image Repository: $imageRepository"
+#         echo "[=] Tag: $(newTag)"
+
+#         # Set the pipeline variables
+#         echo "##vso[task.setvariable variable=imageRepository;]$imageRepository"
+#         echo "##vso[task.setvariable variable=newTag;]$(newTag)" 
+
+#   - task: AzureCLI@2
+#     displayName: PULL IMAGE FROM DEV ACR
+#     inputs:
+#       azureSubscription: $(devServiceConnection)
+#       scriptType: 'bash'
+#       scriptLocation: 'inlineScript'
+#       inlineScript: |
+#         devContainerRegistry="${{ parameters.devContainerRegistry }}"
+
+#         docker image ls
+#         az acr login --name $devContainerRegistry
+#         docker pull $devContainerRegistry.azurecr.io/$(imageRepository):$(newTag)
+#         docker pull $devContainerRegistry.azurecr.io/$(imageRepository):latest
+  
+#   - task: AzureCLI@2
+#     displayName: TAG THE IMAGE CORRECTLY
+#     inputs:
+#       azureSubscription: $(devServiceConnection)
+#       scriptType: 'bash'
+#       scriptLocation: 'inlineScript'
+#       inlineScript: |
+#         devContainerRegistry="${{ parameters.devContainerRegistry }}"
+#         qaContainerRegistry="${{ parameters.qaContainerRegistry }}"
+
+#         docker image ls
+#         docker tag $devContainerRegistry.azurecr.io/$(imageRepository):$(newTag) $qaContainerRegistry.azurecr.io/$(imageRepository):$(newTag)
+#         docker tag $devContainerRegistry.azurecr.io/$(imageRepository):latest $qaContainerRegistry.azurecr.io/$(imageRepository):latest
+#         docker image ls
+        
+#   - task: AzureCLI@2
+#     displayName: PUSH IMAGE TO QA ACR
+#     inputs:
+#       azureSubscription: ${{ parameters.qaServiceConnection }}
+#       scriptType: 'bash'
+#       scriptLocation: 'inlineScript'
+#       inlineScript: |
+#         qaContainerRegistry="${{ parameters.qaContainerRegistry }}"
+#         subscriptionName="${{ parameters.subscriptionName }}"
+
+#         docker image ls
+#         az acr login --name $qaContainerRegistry --subscription $subscriptionName
+#         docker push $qaContainerRegistry.azurecr.io/$(imageRepository):$(newTag)
+#         docker push $qaContainerRegistry.azurecr.io/$(imageRepository):latest
+#         echo "Cleaning docker images"
+#         docker image prune -a -f
+
+    # - ${{ if eq(parameters.changeImageOnWebapp, 'true') }}:
+    #   - task: AzureCLI@2
+    #     displayName: CHANGE IMAGE ON APPSERVICE
+    #     inputs:
+    #       azureSubscription: ${{ parameters.qaServiceConnection }}
+    #       scriptType: 'bash'
+    #       scriptLocation: 'inlinescript'
+    #       inlineScript: |
+    #         az webapp config container set --name ${{ parameters.appName }} --resource-group ${{ parameters.resourceGroupName }} \
+    #         --container-image-name ${{ parameters.qaContainerRegistry }}/${{ parameters.imageRepositoryAndTag }} \
+    #         --container-registry-url https://${{ parameters.qaContainerRegistry }}.azurecr.io
+            
+    # - ${{ if and(eq(parameters.changeImageOnWebapp, true), eq(parameters.performSmokeTest, 'true')) }}:
+    #   - task: Bash@3
+    #     displayName: PERFORM HEALTH CHECK ON APPSERVICE AFTER IMAGE CHANGE
+    #     inputs:
+    #       targetType: 'inline'
+    #       script: |
+    #         sleep 30
+    #         attempt=0
+    #         url="https://${{ parameters.appName }}.azurewebsites.net"
+
+    #         while [ $attempt -lt 5 ]; do
+    #           response=$(curl -s -o /dev/null -w "%{http_code}" $url)
+
+    #           if [ "$response" -eq 200 ]; then
+    #             echo "Health check passed with response code $response"
+    #             exit 0
+    #           else
+    #             echo "Health check failed with response code $response (attempt $((attempt+1))/5)"
+    #             attempt=$((attempt + 1))
+    #             sleep 10
+    #           fi
+    #         done
+            
+    #         echo "Health check failed after 5 attempts"
+    #         exit 1
